services:
  weather-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-dashboard
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}
      - PORT=5000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=2)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
